### ISSUE TITLE
Transition to using intake-esm catalogs

### ISSUE THREAD

**Issue by andersy005** [NCAR/cesm-lens-aws#16]
With the introduction of ESM collection spec: https://github.com/NCAR/esm-collection-spec in conjunction with the rewrite of intake-esm in https://github.com/NCAR/intake-esm/pull/135, it is now easier to transition to using intake-esm instead of intake.  This will make searching, and discovering, data loading of the existing zarr stores in the s3 bucket easier than it is with pure intake.

**Comment by jeffdlb** [comment]
Any update on transition to intake-esm? Intake catalog is essentially unusable without insider knowledge because variable names do not correspond to Zarr store names. :(

Also, please let's do the Intake-ESM work in the v.3 Notebook (which has other changes) instead of the original Notebook.

If there is any way that Brian or I can help we would be glad to do so.

-Jeff DLB
