### ISSUE TITLE
Variables (such as SST, SSH, and others) are all missing values for 20C experiment member 33 at 1938-May-01 

### ISSUE THREAD

**Issue by samclub** [NCAR/cesm-lens-aws#49]
As stated in the title, I found that all variables (such as SST, SSH, and others) on AWS via intake are all missing values for 20C experiment member 33 at 1938-May-01. However, I checked the original dataset on [ESG](https://www.earthsystemgrid.org/dataset/ucar.cgd.ccsm4.CESM_CAM5_BGC_LE.ocn.proc.monthly_ave.html) is good.

Does anyone find a similar problem?

**Comment by jeffdlb** [comment]
Hello-

I believe this is one of the Known Issues with LENS documented at
http://www.cesm.ucar.edu/projects/community-projects/LENS/known-issues.html,
though they mention April 1938 rather than May 1:

"September 2017: It was discovered that numerous monthly ocean variable
timeseries incorrectly contained zeroes as values for member #33
(b.e11.B20TRC5CNBDRD.f09_g16.033) for April 1938 (only). It was determined
that the best course of action is to set all ocean variables for member #33
for April 1938 to the appropriate missing value. The files on the HPSS and
on the ESG have been updated with this fix." [The data on AWS were copied
from ESG after the fix.]

Regards,
Jeff DLB

Jeff de La Beaujardiere, PhD
Director, NCAR/CISL Information Systems Division
https://staff.ucar.edu/users/jeffdlb
https://orcid.org/0000-0002-1001-9210

**Comment by samclub** [comment]
Aloha @jeffdlb,

Well received your response. Thank a lot!

Yes, you are right. The issue appears for April 1938 if it is indicated from times in the filename.
There is known one month off in the times in the file as documented at http://www.cesm.ucar.edu/projects/community-projects/LENS/instructions.html. 

`For monthly time series files note that the time variable is off by one month. For example, if one were to read the fully-coupled control file referenced above(b.e11.B1850C5CN.f09_g16.005.cam.h0.040001-049912.nc), the converted time variable would show that it starts in 40002 (February year 400) and ends in 50001 (January year 500). This is incorrect, in that the file starts in January year 400 and ends in December 499. The times indicated in the file name are correct. If in doubt, consult the time_bnds variable within each file that indicates the beginning and ending dates for the averaging period.
`
Best regards,
Sen Zhao
